---
version: '3'
services:
  base:
    build: base/base
    image: suckowbiz/base
  base-av:
    build: base/av
    image: suckowbiz/base-av
    depends_on:
      - base
  pixum:
    build: pixum
    image: suckowbiz/pixum
    depends_on:
      - "base-av"
