---
version: '2'
services:
  base:
    build: base/base
    image: suckowbiz/base
  base-av:
    build: base/av
    image: suckowbiz/base-av
    depends_on:
      - base
  base-builder:
    build: base/builder
    image: suckowbiz/base-builder
    depends_on:
      - base
  chrome:
    build: chrome
    image: suckowbiz/chrome
    depends_on:
      - "base-av"
  clementine:
    build: clementine
    image: suckowbiz/clementine
    depends_on:
      - "base-av"
  gimp:
    build: gimp
    image: suckowbiz/gimp
    depends_on:
      - "base-av"
  git:
    build: git
    image: suckowbiz/git
    depends_on:
      - "base-builder"
  keepass2:
    build: keepass2
    image: suckowbiz/keepass2
    depends_on:
      - "base-av"
# Disabled because binary must be provided first (see ./idea/README.md)
#  idea:
#    build: idea
#    image: suckowbiz/idea
#    depends_on:
#      - "base-av"
  proxy:
    build: proxy
    image: suckowbiz/proxy
    depends_on:
      - "base"
# Disabled because spss binary must be provided first (see ./spss/README.md)
#  spss:
#    build: spss
#    image: suckowbiz/spss
#    depends_on:
#      - "base"
  steam:
    build: steam
    image: suckowbiz/steam
    depends_on:
      - "base-av"
  supertux:
    build: supertux
    image: suckowbiz/supertux
    depends_on:
      - "base-builder"
