---
version: '3'
services:
  ansible:
    build: ansible/control
    image: suckowbiz/ansible
    depends_on:
      - "ansible-base"
  ansible-base:
    build: ansible/base
    image: suckowbiz/ansible-base
    depends_on:
      - "base"
  ansible-playbook:
    build: ansible/playbook
    image: suckowbiz/ansible-playbook
    depends_on:
      - "ansible-base"
  ansible-vault:
    build: ansible/vault
    image: suckowbiz/ansible-vault
    depends_on:
      - "ansible-base"
  base:
    build: base/base
    image: suckowbiz/base
  base-av:
    build: base/av
    image: suckowbiz/base-av
    depends_on:
      - base
  caddy:
    build: caddy
    image: suckowbiz/caddy
    depends_on:
      - base
  calibre:
    build: calibre
    image: suckowbiz/calibre
    depends_on:
      - "base-av"
  clementine:
    build: clementine
    image: suckowbiz/clementine
    depends_on:
      - "base-av"
  code:
    build: code
    image: suckowbiz/code
    depends_on:
      - "base-av"
  chrome:
    build: chrome
    image: suckowbiz/chrome
    depends_on:
      - "base-av"
  chromix:
    build: chromix
    image: suckowbiz/chromix
    depends_on:
      - "chrome"
  gimp:
    build: gimp
    image: suckowbiz/gimp
    depends_on:
      - "base-av"
  git:
    build: git
    image: suckowbiz/git
    depends_on:
      - "base"
  goland:
    build: goland
    image: suckowbiz/goland
    depends_on:
      - "base-av"
  keepass2:
    build: keepass2
    image: suckowbiz/keepass2
    depends_on:
      - "base-av"
  nginx:
    build: nginx/base
    image: suckowbiz/nginx
    depends_on:
      - "base"
  nginx-php:
    build: nginx/php
    image: suckowbiz/nginx-php
    depends_on:
      - "nginx"
  supertux:
    build: supertux
    image: suckowbiz/supertux
    depends_on:
      - "base"
  tor:
    build: tor
    image: suckowbiz/tor
    depends_on:
      - "base"
  webstorm:
    build: webstorm
    image: suckowbiz/webstorm
    depends_on:
      - "base-av"
